engines:
  csslint:
    enabled: true
  coffeelint:
    enabled: false
  eslint:
    enabled: true
  fixme:
    enabled: false
ratings:
  paths:
  - "**.css"
  - "**.coffee"
  - "**.js"
  - "**.jsx"
exclude_paths:
- tests/**/*
- bower_components/**/*
- examples/**/*
